# Generated by Django 4.2.16 on 2024-10-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reference_date', models.DateField(default='1954-01-01')),
                ('RptDt', models.DateField(default='1954-01-01')),
                ('TckrSymb', models.CharField(default='N/A', max_length=20)),
                ('MktNm', models.CharField(default='N/A', max_length=50)),
                ('SctyCtgyNm', models.CharField(default='N/A', max_length=50)),
                ('ISIN', models.CharField(default='N/A', max_length=12)),
                ('CrpnNm', models.CharField(default='N/A', max_length=255)),
            ],
        ),
    ]
