# Generated by Django 4.2.16 on 2024-10-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RptDt', models.DateField(default='1954-01-01')),
                ('TckrSymb', models.CharField(default='N/A', max_length=20)),
                ('MktNm', models.CharField(default='N/A', max_length=50)),
                ('SctyCtgyNm', models.CharField(default='N/A', max_length=50)),
                ('ISIN', models.CharField(default='N/A', max_length=12)),
                ('CrpnNm', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='CrpnNm',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='ISIN',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='MktNm',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='RptDt',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='SctyCtgyNm',
        ),
        migrations.RemoveField(
            model_name='uploadhistory',
            name='TckrSymb',
        ),
    ]
