# Generated by Django 4.2.16 on 2024-10-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_data_remove_uploadhistory_crpnnm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='failed_rows',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='row_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='row_failed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='row_processed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
